# auto: true
permalink: /p/:title.html
exclude: [ "target", "src", "project.clj", "s3_website.yml" ]
pygments: true
markdown: kramdown
paginate: 5
github: https://github.com/mklappstuhl/martinklepsch.org/commits/master/
